dist: bionic

install:
  - sudo apt-get update
  - sudo apt-get install -y mercurial python3-dev python3-venv
  - sudo apt-get build-dep -y pidgin
  - >
      bash -c '\
        hg clone https://keep.imfreedom.org/pidgin/pidgin \
        && cd pidgin \
        && hg up v2.14.1 \
        && ./autogen.sh \
                --prefix=/usr \
                --disable-nm \
                --with-dynamic-prpls=bonjour,gg,irc,jabber,novell,oscar,sametime,simple,zephyr,null \
                --without-x --disable-gtkspell --disable-gstreamer \
                --disable-vv --disable-meanwhile --disable-avahi \
                --disable-dbus --disable-tcl --disable-gtkui --disable-perl \
        && make -C libpurple -j$(nproc) \
        && sudo make -C libpurple install '
  - rm -rf pidgin

script:
  - make lint
  - make test

notifications:
  email: false
